_import:
  - !include benchmark/tasks/GTZAN/GTZAN_base_config.yaml

dataset:
  pre_extract:
    accelerator: gpu
    audio_dir: data/GTZAN/genres
    output_dir: data/GTZAN/yue_features/yue_feature_default
    keep_folder_structure: true
    overwrite: true

    audio_loader:
      crop_to_length_in_sec: null

    feature_extractor:
      pretrain:
        !include benchmark/models/yue/yue.yaml
      force_half: true

  dataset: GTZAN
  input_type: feature # [audio, feature]
  input_dir: data/GTZAN/yue_features/yue_feature_default
  metadata_dir: data/GTZAN

model:    
    downstream_structure:
      components:
        - name: feature_selector
          layer: 8
          normalized_weight_sum: true 
        - name: mlp
          hidden_layer_sizes: [256]
          dropout_p: 0.2
          num_outputs: 10
  